### ISSUE TITLE
[Bug] 404 errors incorrectly handled

### ISSUE THREAD

**Issue by PadraigHalstead** [bookracy/frontend#39]
### What happened?

When searching for something that doesn't exist this happens:

![image](https://github.com/user-attachments/assets/fa61ba16-09b9-46d9-af5b-fb9b3ff2a298)

### Steps to reproduce?

1. Open the search for a document.
2. Search for something which doesn't exist (for example: "WASDWASD").
3. The Error will show on the screen.

**Comment by rdwxth** [comment]
Done
